In [1]:
import torch
torch.__version__

'2.8.0+cu129'

In [7]:
scalar = torch.tensor([7, 7])
scalar.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[7, 8], [9, 10]])
matrix.ndim

2

In [13]:
tensor = torch.tensor(
    [[[1, 2, 3],
    [3, 6, 9],
    [2, 5, 5]
    ]]
)
tensor.shape

torch.Size([1, 3, 3])

In [21]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.shape

(tensor([[0.9929, 0.7347, 0.4320, 0.8235],
         [0.0909, 0.8632, 0.4408, 0.0519],
         [0.1693, 0.6830, 0.0770, 0.5428]]),
 torch.Size([3, 4]))

In [22]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]))

In [27]:
range = torch.arange(0, 10)
zeros_2 = torch.zeros_like(input=range)
range, zeros_2

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))